### ISSUE TITLE
Option expected only string

### ISSUE THREAD

**Issue by Sandx3** [gs-akhan/react-native-chooser#10]
Is there a possibility to treat Option as a container and place a 'View' or other element in it? It would be really helpful, for example if I want to add some counter of elements that the Select Option contains, like:

```
Select category:
- Comedy          [ 9 ]
- Thriller            [ 7 ]
- Sciene-fiction [ 3 ]
```

**Comment by gs-akhan** [comment]
Hi,Sorry for late reply. 

Try passing <View></View> is it breaking ? If it breaks I will publish a fix tomorrow. 

Thanks

**Comment by Sandx3** [comment]
Yes, it breaks, because Text element requires a string

**Comment by gs-akhan** [comment]
I am fixing it. Thanks
