### ISSUE TITLE
Options Box attached to Select

### ISSUE THREAD

**Issue by jhkersul** [gs-akhan/react-native-chooser#11]
Is there a way to attach the Options Box with Select? Like this:

![Image of Dropdown](https://d13yacurqjgara.cloudfront.net/users/164912/screenshots/2375074/select-boxes-dribbble_1x.png)

**Comment by gs-akhan** [comment]
No as of now it is not. Also on mobile this pattern is not desirable.  It would be better to show selection in larger area taking over the screen.
