### ISSUE TITLE
Components doesn't reflect componentWillReceiveProps 

### ISSUE THREAD

**Issue by technology-studio-apiary** [gs-akhan/react-native-chooser#17]
Select component doesn't reflect componentWillReceiveProps (nextProps: Props). 
When 'selected' prop is changed after component is created, then internal state is not updated.

**Comment by technology-studio-apiary** [comment]
`	componentWillReceiveProps (nextProps) {
		this.selected = nextProps.selected
	  this.setState({
	  	modalVisible : false,
		  defaultText : nextProps.defaultText,
		  selected : nextProps.selected,
		})
	}`


in select.js should do the magic.

**Comment by gs-akhan** [comment]
Can you send a PR ? :)

Thanks

**Comment by technology-studio-apiary** [comment]
Yes, I can, no problem. 

I’ll send it in two days time, when i’ll have more time. I have horrible deadline to meet.

**Comment by rostislav-simonik** [comment]
https://github.com/gs-akhan/react-native-chooser/pull/18
