### ISSUE TITLE
[1.5.1] Broken when using defaultText

### ISSUE THREAD

**Issue by st0ffern** [gs-akhan/react-native-chooser#19]
When a default prop is passed to the `Select` component in example here:
```js
<Select
  onSelect = {d => this.props.onChange({farm : d})}
  defaultText  = "Choose"
  {
    this.state.farms.map((farm, key) => 
      <Option value={farm.id} key={key}>{farm.name}</Option>
    )
  }
</Select>
```
This will render the input selected to defaultText and not the selected value.

Making a PR to fix it

**Comment by technology-studio-apiary** [comment]
The issue is that there must be different state attribute e.g. 'currentValue' to hold currently selected value. 	

this is what causes the issue: 
`setSelectedText(text){
	this.setState({
		**defaultText: text**
	})
}`



`
		<View style={styles.selectBoxContent}>
			<Text style = {textStyle}>{**this.state.defaultText**}</Text>
			<Indicator direction={indicator} color={indicatorColor} size={indicatorSize} style={indicatorStyle} />
		</View>`



and given attribute must be initialised with  defaultText only within constructor, nowhere else.

**Comment by st0ffern** [comment]
If you initialize the Select with `defaultText` and the master component rerenders, the Select will fall back to the defaultText..

**Comment by technology-studio-apiary** [comment]
quick fix is to remove  defaultText assignment from this. But as i said,  to use defaultText as variable to hold current state is dirty. 
 
componentWillReceiveProps (nextProps) {
		this.selected = nextProps.selected
		this.setState({
		  modalVisible : false,
		  defaultText : nextProps.defaultText,
		  selected : nextProps.selected,
		})
	}

**Comment by st0ffern** [comment]
Then you should remove `defaultText` input from the docs and the component..

**Comment by technology-studio-apiary** [comment]
No ,we don't understand each other.  Property is fine on props level, the issue is that state of the component contains  attribute of the same name, and it's rewritten in componentWillReceiveProps. Let me do PR, to fix this issue.

**Comment by technology-studio-apiary** [comment]
Your pull request #20, commit  e57fc4ccf71feff5b82785ef8a5ee91c047edac0, returns back the original issue where component is not reflected when props are changed after mounting.

**Comment by gs-akhan** [comment]
@stoffern  was it broken in 1.5.1 ? And did not worked at all ?

**Comment by gs-akhan** [comment]
Yes, When parent component is rerendering it is breaking.  @technology-studio-apiary  you want to revert that. Or should I ?

Thanks

**Comment by gs-akhan** [comment]
Hi All. 
I have reverted that because we use this in Company's production app. We can figure this out once we have all consensus 
Thanks :)

**Comment by gs-akhan** [comment]
Version 1.5.2 I've published  it
