### ISSUE TITLE
iOS Landscape-only error

### ISSUE THREAD

**Issue by Monteiro4** [gs-akhan/react-native-chooser#24]
"Modal was presented with 0x2 orientations mask but the application only supports 0x18. Add more interface orientations to your app's Info.plist to fix this.NOTE: this will crash in non-dev mode."

My app can only be presented in Landscape, so in my Info.plist I only have the landscape options... and using this library it throws this error when opening the modal.
In Android everything works fine. Is there any workaround?

**Comment by st0ffern** [comment]
have you tested the v2 branch?

Feel free to check it out and see if that fixes the issue.

**Comment by Monteiro4** [comment]
Thanks for the suggestion, but it throws the same error :(

I'm running react-native 0.42.0-rc.2, I will try to update to see if it fixes

**Comment by ShongSu** [comment]
I am having the same problem, any idea on how to make it work on iOS Landscape?

**Comment by gs-akhan** [comment]
I am sorry for this. I haven't got time to fix this. If anyone can help on this. I will be more than happy to merge it

Thanks

**Comment by ShongSu** [comment]
I just made a PR to master, please review and test it :)

**Comment by gs-akhan** [comment]
Thank you Sir, 
Did you get a chance to test it once ? Sure I will do it right away 

Thanks

**Comment by ShongSu** [comment]
Yes. It works on my project.
Before fix: 
![simulator screen shot 2017 8 26 7 46 26](https://user-images.githubusercontent.com/13125649/29746105-264d85d2-8a9d-11e7-8c0d-18ef74523bc8.png)
After fix:
![simulator screen shot 2017 8 26 7 45 39](https://user-images.githubusercontent.com/13125649/29746106-2ccb3166-8a9d-11e7-9d2d-1eb375628ebc.png)

**Comment by gs-akhan** [comment]
Amazing. just testing it here as well. will merge once I am done in few
mins.

:)

**Comment by ShongSu** [comment]
Cool, thanks.

**Comment by gs-akhan** [comment]
Published 1.6.1 .. 
> npm install react-native-chooser@1.6.1

Thanks again.. :)
