### ISSUE TITLE
Updating default text after property change

### ISSUE THREAD

**Issue by Sergey-Shapovalov** [gs-akhan/react-native-chooser#26]
Hi,

I experience an issue when updating the chooser after the selected item is set outside the chooser code. Example:
`SomeComponent extends Component {
  render () {
    return (
      <Select
        defaultText="Tap to choose"
      >
    )
  }
}`

**Comment by gs-akhan** [comment]
Hi,
Is it not setting the value back into the component ?

**Comment by Sergey-Shapovalov** [comment]
Sorry, one moment, I've occasionally pressed enter :-)

**Comment by Sergey-Shapovalov** [comment]
The idea is that if I programmatically set the selected prop of the component to null, which should normally clear the displayed text and return it back to the defaultText, it doesn't actually update. It happens because you use this.state.defaultText as the source of the text displayed in the dropdown box and you only update it in the constructor or in the onSelect method. 

The problem may be solved by updating it in the componentWillReceiveProps method, like this:

> componentWillReceiveProps (nextProps) {
		if (nextProps.selected == null)
			this.setState({
				defaultText: nextProps.defaultText
			})
	}

**Comment by gs-akhan** [comment]
Makes sense.. Can I have a PR ? 

Thanks..

**Comment by gs-akhan** [comment]
@stoffern Any thoughts ?

**Comment by ask007learning** [comment]
I am trying to update it using props and it doesn't work.  I tried using setSelectedText and it doesn't work either.

**Comment by gs-akhan** [comment]
@ask007learning  @Sergey-Shapovalov 
Shipped. please upgrade. 

npm install react-native-chooser@1.5.3 --save

Thanks
