### ISSUE TITLE
 Use the prop-types package instead of React.PropTypes

### ISSUE THREAD

**Issue by xinhash** [gs-akhan/react-native-chooser#30]
Hi, I'm getting a warning regarding the deprecation of React.PropTypes. Can you please update the package with same.

**Comment by gs-akhan** [comment]
Hi,
If possible can you send me a PR. 

Thanks

**Comment by xinhash** [comment]
I've sent a PR

**Comment by gs-akhan** [comment]
Thanks, I have merged it,, just have to run some manual tests before I actually publish it tomorrow. 
 :)

**Comment by gs-akhan** [comment]
Published 1.6.0
Thanks for all your hard work
