### ISSUE TITLE
Schedule of releasing commits into npm

### ISSUE THREAD

**Issue by hirejohnsalcedo** [gs-akhan/react-native-chooser#39]
Hi @gs-akhan , on [npm](https://www.npmjs.com/package/react-native-chooser), `1.6.2` published 3 weeks ago is still the latest version. When would we publish the new repo with the latest commit? Thanks.

**Comment by gs-akhan** [comment]
I will do this tomorrow morning,
Thanks

**Comment by hirejohnsalcedo** [comment]
@gs-akhan hello, friend. will you have time to publish today? thank you!

**Comment by gs-akhan** [comment]
Done, Published.
