### ISSUE TITLE
Change State value doesnt change description text 

### ISSUE THREAD

**Issue by wcsouza** [gs-akhan/react-native-chooser#41]
How can I change the value programatically?

If I call setState({value: 'Some value'}) does not reflect on component text

**Comment by gs-akhan** [comment]
You have to pass it as a default text again to the component. 

```
<select defaultText = {this.state.value}>
</select>
```

**Comment by wcsouza** [comment]
Oh, yes, sure. I'm sorry i didn't say what i tried.

I'm using defaultText={this.state.value} but its not refreshing the text. I saw others issues about it but didnt find any solution.

**Comment by gs-akhan** [comment]
CAn you just paste a minimal example code here that I can just paste and
run .

that would help me a lot

**Comment by wcsouza** [comment]
I was using state to handle the text, then I moved to redux and now is working

I'm sorry for waste your time

**Comment by gs-akhan** [comment]
No worries .. if it happens again feel free to open it..
