### ISSUE TITLE
Customize Option

### ISSUE THREAD

**Issue by IsharaHansaka** [gs-akhan/react-native-chooser#52]
Hi,

I'm just wondering how to add a cancel button in option. Can i customize option something like in the screenshot?
![select options](https://user-images.githubusercontent.com/38131334/40308297-63acfaee-5d23-11e8-9462-7f61c277c835.jpg)

**Comment by gs-akhan** [comment]
The option take only text and it is wrapped inside a ```<Test />``` component. 
https://github.com/gs-akhan/react-native-chooser/blob/master/lib/option.js#L23

If you pass a ```<Text />``` and style it. you can do it.
