### ISSUE TITLE
How do you preselect an option?

### ISSUE THREAD

**Issue by strataga** [gs-akhan/react-native-chooser#8]
```
<Select defaultText="Select Status"
     indicator="down"
     style={styles.select}
     onSelect = {this.onStatusSelect.bind(this, question.id)}>
     <Option value="SAT">SAT</Option>
     <Option value="UNS">UNS</Option>
     <Option value="NA">NA</Option>
</Select>
```

**Comment by gs-akhan** [comment]
You have to set "defaultText" property. to the text to be shown. You can maintain this pre-selected option in state of your component. 
I will add a property for selected today. 
Thanks

**Comment by strataga** [comment]
Awesome! Thank you!

**Comment by gs-akhan** [comment]
I am not getting any use-case where preselect can be used. You can always set the `defaultText` to display the selected one. 

If you have any idea to make API simpler I would love to add it. 

Thanks

**Comment by strataga** [comment]
Yeah maybe I was confused on what the default text would be used for. That works for my use-case. But, it might be nice to show some sort of indicator or allow a css style on the one that is currently selected in the modal.

**Comment by gs-akhan** [comment]
Done. Added two more props 
```
selectedStyle  = {{backgroundColor : "red"}} 
selected = "johnceena"
```

These props are on `<Select />` component.  if the value matches the selected one. The style is applied. 
Also version 1.3.0 is published on NPN.

`npm i react-native-chooser --save` to update. 

Thanks.

**Comment by strataga** [comment]
Perfect! Thank you!
