### ISSUE TITLE
How to style option separators?

### ISSUE THREAD

**Issue by justinireland** [gs-akhan/react-native-chooser#9]
My option list is showing black line separators between each option item.

I've set borderWidth to 0 for both the optionList and the style of each option item but I'm still seeing some kind of border/separator between each item in the list. How can I access/disable this?

I noticed the example animation doesn't show this though.

**Comment by gs-akhan** [comment]
Alright. I will see into this and update this ticket.

**Comment by gs-akhan** [comment]
Hi, I have removed that default border and published on npm too. Please update to see the effect. 

Just pass `style` prop to each `<Option />`  to style them.. 

Thanks.. please reopen if you see any other issue. 
Have a nice day .
